### ISSUE TITLE
Khởi tạo dự án

### ISSUE THREAD

**Issue by tudn9x** [tudn9x/project-no2#4]
- [x] Khởi tạo repo
- [x] Khởi tạo zenhub
- [x] Demo site
- [x] Tài liệu, quy trình
- [x] Mô tả yêu cầu
- [x] Design Database
